# 학습 전용 Dockerfile
FROM openjdk:17-slim

# Python 설치
RUN apt-get update && \
    apt-get install -y python3 python3-pip git && \
    apt-get clean

# 작업 디렉토리
WORKDIR /app

# requirements 설치
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# 소스 코드 복사
COPY wine_pyspark.py .
COPY wine_quality_merged.csv .

# MLflow 아티팩트 폴더를 외부와 공유
VOLUME ["/app/mlruns"]

# 학습 스크립트 실행
CMD ["python3", "wine_pyspark.py"]
